In [111]:
import pandas as pd
import numpy as np

In [112]:
data = pd.read_csv("/Users/ShivaGanga/Documents/Masters/Spring17/MLAnurag/Assignments/Assignment5/car.data.txt",header = None,names = ['buying','maint','doors','persons','lug_boot','safety','cat'])

In [113]:
print data.info()
print data.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
buying      1728 non-null object
maint       1728 non-null object
doors       1728 non-null object
persons     1728 non-null object
lug_boot    1728 non-null object
safety      1728 non-null object
cat         1728 non-null object
dtypes: object(7)
memory usage: 94.6+ KB
None
  buying  maint doors persons lug_boot safety    cat
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc
5  vhigh  vhigh     2       2      med   high  unacc
6  vhigh  vhigh     2       2      big    low  unacc
7  vhigh  vhigh     2       2      big    med  unacc
8  vhigh  vhigh     2       2      big   high  unacc
9  vhigh  vhigh     2       4    small    low  unacc

In [114]:
data['buying'] = data['buying'].map({'vhigh' : 3,'high' : 2, 'med' : 1, 'low' : 0})
data['maint'] = data['maint'].map({'vhigh' : 3,'high' : 2, 'med' : 1, 'low' : 0})
data['doors'] = data['doors'].map({'5more' : 5, '2' : 2,'3' : 3, '4' : 4})
data['persons'] = data['persons'].map({'more' : 5, '2' : 2, '4' : 4})
data['lug_boot'] = data['lug_boot'].map({'small' : 0,'med' : 1, 'big' : 2})
data['safety'] = data['safety'].map({'low' : 0,'med' : 1, 'high' : 2})
data['cat'] = data['cat'].map({'unacc' : 0,'acc' : 1,'good' : 2,'vgood' : 3})

In [115]:
#msk = np.random.rand(len(data)) < 0.7
#train = data[msk]
#test = data[~msk]
train =data.sample(frac = 0.7)
test = data.loc[~data.index.isin(train.index)]
train

      buying  maint  doors  persons  lug_boot  safety  cat
660        2      1      2        4         1       0    0
653        2      1      2        2         1       2    0
982        1      2      2        4         0       1    0
1444       0      2      3        4         1       1    1
436        2      3      2        2         1       1    0
131        3      2      2        5         1       2    0
305        3      1      5        2         2       2    0
1580       0      1      4        4         1       2    3
1727       0      0      5        5         2       2    3
342        3      0      2        5         0       0    0
1642       0      0      2        5         1       1    1
577        2      2      3        4         0       1    0
234        3      1      2        5         0       0    0
567        2      2      3        2         0       0    0
217        3      1      2        2         0       1    0
1560       0      1      3        5         1       0    0
1627       0      0      2        2         2       1    0
153        3      2      3        5         0       0    0
226        3      1      2        4         0       1    0
1634       0      0      2        4         1       2    2
341        3      0      2        4         2       2    1
1720       0      0      5        5         0       1    1
566        2      2      2        5         2       2    1
409        3      0      5        2         1       1    0
1350       0      3      4        2         0       0    0
1056       1      2      5        2         1       0    0
1339       0      3      3        4         2       1    1
704        2      1      4        2         0       2    0
930        1      3      4        4         1       0    0
1629       0      0      2        4         0       0    0
...      ...    ...    ...      ...       ...     ...  ...
1263       1      0      4        5         1       0    0
1515       0      1      2        2         1       0    0
49         3      3      3        5         1       1    0
1111       1      1      3        2         1       1    0
1715       0      0      5        4         1       2    3
956        1      3      5        4         0       2    1
373        3      0      3        5         1       1    1
261        3      1      3        5         0       0    0
1107       1      1      3        2         0       0    0
228        3      1      2        4         1       0    0
1477       0      2      4        5         0       1    1
1294       1      0      5        5         2       1    2
1571       0      1      4        2         1       2    0
471        2      3      3        4         1       0    0
146        3      2      3        4         0       2    0
1382       0      3      5        2         1       2    0
1204       1      0      2        4         2       1    2
1593       0      1      5        2         0       0    0
169        3      2      4        2         2       1    0
1543       0      1      3        2         1       1    0
139        3      2      3        2         1       1    0
832        2      0      4        5         1       1    1
441        2      3      2        4         0       0    0
414        3      0      5        4         0       0    0
205        3      2      5        4         2       1    0
113        3      2      2        2         1       2    0
789        2      0      3        2         2       0    0
230        3      1      2        4         1       2    1
601        2      2      4        2         2       1    0
1322       0      3      2        5         2       2    1

[1210 rows x 7 columns]

In [116]:
from sklearn.metrics import accuracy_score, log_loss
from sklearn import tree
from sklearn import linear_model
from sklearn import svm
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
x_train = train[train.columns[0:6]]
y_train  = train[train.columns[6]]
x_test = test[test.columns[0:6]]
y_test = test[test.columns[6]]
x_train

      buying  maint  doors  persons  lug_boot  safety
660        2      1      2        4         1       0
653        2      1      2        2         1       2
982        1      2      2        4         0       1
1444       0      2      3        4         1       1
436        2      3      2        2         1       1
131        3      2      2        5         1       2
305        3      1      5        2         2       2
1580       0      1      4        4         1       2
1727       0      0      5        5         2       2
342        3      0      2        5         0       0
1642       0      0      2        5         1       1
577        2      2      3        4         0       1
234        3      1      2        5         0       0
567        2      2      3        2         0       0
217        3      1      2        2         0       1
1560       0      1      3        5         1       0
1627       0      0      2        2         2       1
153        3      2      3        5         0       0
226        3      1      2        4         0       1
1634       0      0      2        4         1       2
341        3      0      2        4         2       2
1720       0      0      5        5         0       1
566        2      2      2        5         2       2
409        3      0      5        2         1       1
1350       0      3      4        2         0       0
1056       1      2      5        2         1       0
1339       0      3      3        4         2       1
704        2      1      4        2         0       2
930        1      3      4        4         1       0
1629       0      0      2        4         0       0
...      ...    ...    ...      ...       ...     ...
1263       1      0      4        5         1       0
1515       0      1      2        2         1       0
49         3      3      3        5         1       1
1111       1      1      3        2         1       1
1715       0      0      5        4         1       2
956        1      3      5        4         0       2
373        3      0      3        5         1       1
261        3      1      3        5         0       0
1107       1      1      3        2         0       0
228        3      1      2        4         1       0
1477       0      2      4        5         0       1
1294       1      0      5        5         2       1
1571       0      1      4        2         1       2
471        2      3      3        4         1       0
146        3      2      3        4         0       2
1382       0      3      5        2         1       2
1204       1      0      2        4         2       1
1593       0      1      5        2         0       0
169        3      2      4        2         2       1
1543       0      1      3        2         1       1
139        3      2      3        2         1       1
832        2      0      4        5         1       1
441        2      3      2        4         0       0
414        3      0      5        4         0       0
205        3      2      5        4         2       1
113        3      2      2        2         1       2
789        2      0      3        2         2       0
230        3      1      2        4         1       2
601        2      2      4        2         2       1
1322       0      3      2        5         2       2

[1210 rows x 6 columns]

In [117]:
clf = tree.DecisionTreeClassifier()
dt_clf = clf.fit(x_train,y_train)
dt_predict = dt_clf.predict(x_test)
dt_acc = accuracy_score(y_test,dt_predict)
print 'DecisionTree accuracy :', dt_acc

clf = linear_model.Perceptron()
pt_clf = clf.fit(x_train,y_train)
pt_predict = pt_clf.predict(x_test)
pt_acc = accuracy_score(y_test,pt_predict)
print 'Perceptron accuracy :',pt_acc


clf = MLPClassifier()
nn_clf = clf.fit(x_train,y_train)
nn_predict = nn_clf.predict(x_test)
nn_acc = accuracy_score(y_test,nn_predict)
print 'Neural Net accuracy :',nn_acc

clf = svm.SVC()
svm_clf = clf.fit(x_train,y_train)
svm_predict = svm_clf.predict(x_test)
svm_acc = accuracy_score(y_test,svm_predict)
print 'SVM accuracy :',svm_acc



clf = GaussianNB()
nb_clf = clf.fit(x_train,y_train)
nb_predict = nb_clf.predict(x_test)
nb_acc = accuracy_score(y_test,nb_predict)
print 'naïve Bayes accuracy :',nb_acc


clf = LogisticRegression()
lr_clf = clf.fit(x_train,y_train)
lr_predict = lr_clf.predict(x_test)
lr_acc = accuracy_score(y_test,lr_predict)
print 'Logistic Regression accuracy :',lr_acc


clf = KNeighborsClassifier(3)
knn_clf = clf.fit(x_train,y_train)
knn_predict = knn_clf.predict(x_test)
knn_acc = accuracy_score(y_test,knn_predict)
print 'k-Nearest Neighbors accuracy :',knn_acc


clf = BaggingClassifier()
bg_clf = clf.fit(x_train,y_train)
bg_predict = bg_clf.predict(x_test)
bg_acc = accuracy_score(y_test,bg_predict)
print 'Bagging accuracy :',bg_acc


clf = RandomForestClassifier()
rf_clf = clf.fit(x_train,y_train)
rf_predict = rf_clf.predict(x_test)
rf_acc = accuracy_score(y_test,rf_predict)
print 'Random Forests :',rf_acc


clf = AdaBoostClassifier()
ada_clf = clf.fit(x_train,y_train)
ada_predict = ada_clf.predict(x_test)
ada_acc = accuracy_score(y_test,ada_predict)
print 'AdaBoost accuracy :',ada_acc


clf = GradientBoostingClassifier()
gb_clf = clf.fit(x_train,y_train)
gb_predict = gb_clf.predict(x_test)
gb_acc = accuracy_score(y_test,gb_predict)
print 'Gradient Boosting accuracy :',gb_acc

DecisionTree accuracy : 0.976833976834
Perceptron accuracy : 0.714285714286
Neural Net accuracy : 0.915057915058
SVM accuracy : 0.959459459459
naïve Bayes accuracy : 0.766409266409
Logistic Regression accuracy : 0.80694980695
k-Nearest Neighbors accuracy : 0.918918918919
Bagging accuracy : 0.978764478764
Random Forests : 0.96332046332
AdaBoost accuracy : 0.849420849421
Gradient Boosting accuracy : 0.976833976834